### ISSUE TITLE
[Bug] iOS Podcast app reported as OS X Media Component

### ISSUE THREAD

**Issue by jamesmontemagno** [firesidelabs/fireside#89] opened 2017-02-09 23:18 UTC
Under iOS the Apple iOS podcast app is no where to be found. From my statistics I have found that they are showing up as OS X Media Component under OS X

**Comment by dan** [comment] 2017-02-10 17:31
This is a duplicate of https://github.com/firesidelabs/fireside/issues/78.

**Closed by dan** 2017-02-10 17:31 UTC

**Comment by jamesmontemagno** [comment] 2017-02-10 17:44
@dan that one was for Mobile Safari.. This one actually comes in as OS X Media Component. 

![image](https://cloud.githubusercontent.com/assets/1676321/22837433/627b8522-ef75-11e6-8d26-aa5d6fe44a4e.png)


I do see a "Mobile Safari", but it is much smaller and in a different group.

**Comment by dan** [comment] 2017-02-18 20:49
Thanks, we're still looking into this!
