### ISSUE TITLE
Feature: metrics graph of downloads per day

### ISSUE THREAD

**Issue by danbetcher** [firesidelabs/fireside#76] opened 2016-12-19 17:44 UTC
In the metrics tab for any given episode, as well as for all episodes overall, it would be nice to see a graph of downloads per day (rather than just total downloads) so we could visualize the popularity and longevity of an episode over time.  It would be nice to be able to compare which episodes are of interest long-term vs. ones that are only interesting for a short period of time after release.   I'm thinking about episodes that relate to current events or news vs. more ever-green content like guides or tutorials that would still be relevant long after the episode originally aired.

**Comment by dan** [comment] 2017-02-09 22:50
This is similar/duplicate of https://github.com/firesidelabs/fireside/issues/73.

**Closed by dan** 2017-02-09 22:50 UTC
