### ISSUE TITLE
Customizable Image when Sharing Episode

### ISSUE THREAD

**Issue by tcgannon** [firesidelabs/fireside#96] opened 2017-02-22 17:06 UTC
When sharing the episode URL, the user may want to specify whether to use the Cover Art, the Header Image (both as specified on the admin page for the episode) or it may be that they want to upload other art that is used instead of these two.

**Comment by vallieres** [comment] 2017-02-22 19:17
Kind of a dupe of  #86. I would love this as we do have custom social images we used to share. This image is 16:9 and fits well in timelines (twitter, fb, linkedin, etc)

**Closed** 2017-07-24 22:10 UTC
